name       : python-evdev
version    : 1.1.2
release    : 6
source     :
    - https://github.com/gvalkov/python-evdev/archive/v1.1.2.tar.gz : 4403d4ee2d9682d17d292d5cfe0781d9ebfe119c7bb0f631fb59de3003bad49d
license    : BSD-3-Clause
component  : programming.python
summary    : Python bindings for the Linux input subsystem
builddeps  :
    - pkgconfig(python3)
    - python-pytest
description: |
    This package provides bindings to the generic input event interface
    in Linux. The evdev interface serves the purpose of passing events
    generated in the kernel directly to userspace through character
    devices that are typically located in /dev/input/.

    This package also comes with bindings to uinput, the userspace input
    subsystem. Uinput allows userspace programs to create and handle
    input devices that can inject events directly into the input subsystem.
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test py.test -v -k "not test_uinput"
    %python3_test py.test3 -v -k "not test_uinput"
