name       : python-evdev
version    : 0.6.4
release    : 2
source     :
    - https://github.com/gvalkov/python-evdev/archive/v0.6.4.tar.gz : a84b6538885770a6e0ebefb1a65d138d485a13002452bfdd537b07f146af2bd9
license    : BSD-3-Clause
component  : programming.python
summary    : Python bindings for the Linux input subsystem
builddeps  :
    - pkgconfig(python3)
description: |
    This package provides bindings to the generic input event interface
    in Linux. The evdev interface serves the purpose of passing events
    generated in the kernel directly to userspace through character
    devices that are typically located in /dev/input/.

    This package also comes with bindings to uinput, the userspace input
    subsystem. Uinput allows userspace programs to create and handle
    input devices that can inject events directly into the input subsystem.
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
